### ISSUE TITLE
create static website

### ISSUE THREAD

**Issue by JacobMcElhinney** [JacobMcElhinney/static-website#1]
## summary
Recreate [agilemanifesto.org](https://agilemanifesto.org/).

## description
create two pages (html documents), one for the agile manifesto and one for the twelve principles behind. The user should be able to navigate between the two.

**Task List**
- [ ] create and markup content in index.html
- [ ] create and markup content in principles.html
- [ ] add hyperlink for navigation between pages.
- [ ] create and apply global CSS styles
